# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caaed42d127639ebfe673fea46669cce2179861fdef970ed3275f2c63b4370b2da5cf268ef5826620dd0a2ff1b93e526cf8eda8bbea2646ff742befff2ef2580

test:
  secret_key_base: baae530ca509d938a0016c1329cf7eeda34995f9435c9b8d1e37f33ca3d61986ddb58850038086a31005816865fe75748beac167af3494335d6ae1009ba7a815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
